### PR TITLE
Changed mod name to ensure compatibility with repository fortran-string.

### PR DESCRIPTION
**Pull request by JHenneberg**
The string_mod is not compatabile with the new repository fortran_string. Deleting the file will cause a circular dependency. Maybe you have an better idea then my attempt?

### CODE REVIEW

**Comment by JHenneberg** [comment]
The string_mod is not compatabile with the new repository fortran_string. Deleting the file will cause a circular dependency. Maybe you have an better then my attempt?

**Comment by dongli** [comment]
Hi, what incompatible issues do you mean? I can build `fortran-string` and other repositories that depend on `fortran-unit-test` successfully.

**Comment by JHenneberg** [comment]
```fortran-unit-test``` can be build individually but not in combination with ```fortran-string``` there is a problem because ```fortran-unit-test``` and ```fortran-string``` are using different modules with the same name ```string_mod```. This is causing an error (LNK2005: _STRING_MOD. already defined in fortran-string.lib(string_mod.obj)) while linking because ```string_test.f90``` is depending on ```fortran-unit-test```.

**Comment by dongli** [comment]
I will try to refactor `fortran-unit-test`. Thanks for reporting!

**Comment by dongli** [comment]
I have refactored the codes by merging `log_mod.F90` and `string_mod.F90` into `test_common_mod.F90`. I also split `test_case` and `test_suite` into two modules.

**Pull request closed without merging**
