### PR TITLE
added function test_case_get_assert_results()

### PR DESCRIPTION
**Pull request by JHenneberg**

### CODE REVIEW

**Comment by dongli** [comment]
Please add some description about the new feature :)

**Comment by JHenneberg** [comment]
Sure. To be able to use this fortran unit testing framework in a CI System more convinient I wrote this routine. 

In general I am writing a specific module for testing which looks similar to the following:
```fortran
module myTests_mod
  use unit_test
  use myTests
  implicit none
  private
  public :: myTests

  type(test_suite_type) :: SUITE
contains
  subroutine myTests(passed)
    implicit none

    logical(4), intent(inout), optional :: passed

    logical(4), allocatable :: asserts(:)

    SUITE%name = 'myTests_mod'

    call test_subroutine1()
    call test_subroutine2()

    if (present(passed)) then
      asserts = test_suite_get_assert_results(SUITE)
      passed = merge(.true., .false., all(asserts))
    else
      call test_suite_report(SUITE)
    end if
  end subroutine myTests


  subroutine test_subroutine1(passed)
    !DEC$ ATTRIBUTES DLLEXPORT :: test_subroutine1
    implicit none

    logical(4), optional, intent(inout) :: passed

    call test_case_create('subroutine1', SUITE)

    call assert_equal(INT(1, 4), INT(1, 4), __FILE__, __LINE__, SUITE)

    if (present(passed)) &
      passed = all(test_case_get_assert_results('subroutine1', SUITE))
  end subroutine test_subroutine1


  subroutine test_subroutine2(passed)
    !DEC$ ATTRIBUTES DLLEXPORT :: test_subroutine2
    implicit none

    logical(4), optional, intent(inout) :: passed

    call test_case_create('subroutine2', SUITE)

    call assert_equal(INT(1, 4), INT(1, 4), __FILE__, __LINE__, SUITE)
    call assert_equal(INT(1, 4), INT(1, 4), __FILE__, __LINE__, SUITE)

    if (present(passed)) &
      passed = all(test_case_get_assert_results('subroutine2', SUITE))
  end subroutine test_subroutine2
end module myTests_mod
```

I have a `program` calling `myTests` to evaulate the results while programming. The logical, optional variable `passed` is not used inside of fortran.

I have an additional C# unit testing project which is natevly supported in various CI Systems. This project is consuming the fortran.dll, is calling the exported subroutines and evaluates them automatically.

```C#
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Runtime.InteropServices;

namespace myTests
{
    [TestClass]
    public class myTests
    {
        [TestMethod]
        public void subroutine1()
        {
            bool passed = false;
            NativeMethods.subroutine1(ref passed);
            Assert.IsTrue(passed);
        }
        [TestMethod]
        public void subroutine2()
        {
            bool passed = false;
            NativeMethods.subroutine2(ref passed);
            Assert.IsTrue(passed);
        }
    }

    public static class NativeMethods
    {
        [DllImport(
            @"myTests.dll",
            CallingConvention = CallingConvention.Cdecl,
            CharSet = CharSet.Ansi,
            EntryPoint = "MYTESTS_MOD_mp_SUBROUTINE1")]
        public static extern void subroutine1(ref bool passed);
        [DllImport(
            @"myTests.dll",
            CallingConvention = CallingConvention.Cdecl,
            CharSet = CharSet.Ansi,
            EntryPoint = "MYTESTS_MOD_mp_SUBROUTINE2")]
        public static extern void subroutine2(ref bool passed);
    }
}

```

**Comment by dongli** [comment]
Thanks for providing more information! So you need to gather the results of asserts in a suite, and let external caller decide how to handle the errors. I think this is great.

**Comment by JHenneberg** [comment]
Exactly. You can either test the complete suite by calling `myTests` or the seperate subroutines `subroutine1`. In the CI system (we are using TeamCity) you can examine which tests failed and which succeded and if necessary go back to your fortran code and fix it.

**Pull request merged**
