### PR TITLE
reworked float comparioson

### PR DESCRIPTION
**Pull request by JHenneberg**
https://floating-point-gui.de/errors/comparison/

### CODE REVIEW

**Comment by dongli** [comment]
The following assertions in `test_assert.F90` fail:
```Fortran
...
185: call assert_great_than([1.0D0, 1.0D0], [0.0D0, 2.0D0], __FILE__, __LINE__, test_suite_great_than)
188: call assert_great_than(reshape([1.0, 1.0, 1.0, 1.0], [2, 2]), reshape([0.0, 2.0, 0.0, 0.0], [2, 2]), __FILE__, __LINE__, test_suite_great_than)
190: call assert_great_than(reshape([1.0D0, 1.0D0, 1.0D0, 1.0D0], [2, 2]), reshape([0.0D0, 2.0D0, 0.0D0, 0.0D0], [2, 2]), __FILE__, __LINE__, test_suite_great_than)
```

**Comment by dongli** [comment]
I have merged your changes in this PR, and made some code refactors. Could you investigate the above errors in `test_assert.F90` in other PR? Thanks!

**Comment by JHenneberg** [comment]
good morning,
this asserts should fail no? I created examples for testing which are causing an error and then other example which should pass.
[1.0D0, 1.0D0] > [0.0D0, 2.0D0] is false because A[2] > B[2] is false, so the assertion fails. Do I miss something? This is my result (half fail, half pass as intended):

```
///////////////////////// Report of Suite: Approximate //////////////////////////

 +-> Details:
 |   |
 |   +-> real: 12 of 24 assertions succeed.
 |   |   |
 |   |   +-> Assertion #1 failed with reason: x ( 1.000) =~ y ( 2.000)
 |   |   +-> Check line: Unknown file:-1
 |   |   |
 |   |   +-> Assertion #3 failed with reason: x ( 1.000) =~ y ( 1.100)
 |   |   +-> Check line: Unknown file:-1
 |   |   |
 |   |   +-> Assertion #5 failed with reason: x ( 1.000) =~ y ( 1.100)
 |   |   +-> Check line: Unknown file:-1
 |   |   |
 |   |   +-> Assertion #7 failed with reason: x ( 1.000) =~ y ( 1.100)
 |   |   +-> Check line: Unknown file:-1
 |   |   |
 |   |   +-> Assertion #9 failed with reason: x ( 1.000) =~ y ( 1.100)
 |   |   +-> Check line: Unknown file:-1
 |   |   |
 |   |   +-> Assertion #11 failed with reason: x ( 1.000) =~ y ( 1.100)
 |   |   +-> Check line: Unknown file:-1
 |   |   |
 |   |   +-> Assertion #13 failed with reason: x ( 1.000) =~ y ( 1.100)
 |   |   +-> Check line: Unknown file:-1
 |   |   |
 |   |   +-> Assertion #15 failed with reason: x ( 1.000) =~ y ( 1.100)
 |   |   +-> Check line: Unknown file:-1
 |   |   |
 |   |   +-> Assertion #17 failed with reason: x ( 1.000) =~ y ( 1.100)
 |   |   +-> Check line: Unknown file:-1
 |   |   |
 |   |   +-> Assertion #19 failed with reason: x ( 1.000) =~ y ( 1.100)
 |   |   +-> Check line: Unknown file:-1
 |   |   |
 |   |   +-> Assertion #21 failed with reason: x ( 1.000) =~ y ( 1.100)
 |   |   +-> Check line: Unknown file:-1
 |   |   |
 |   |   +-> Assertion #23 failed with reason: x ( 1.000) =~ y ( 1.100)
 |   |   +-> Check line: Unknown file:-1
 |   |
 |
 +-> Summary:
 |   +-> Approximate: 12 of 24 assertions succeed.

////////////////////////////////////////////////////////////////////////////////


/////////////////////////// Report of Suite: Boolean ////////////////////////////

 +-> Details:
 |   |
 |   +-> false: 1 of 2 assertions succeed.
 |   |   |
 |   |   +-> Assertion #1 failed with reason: x (true) false y (N/A)
 |   |   +-> Check line: test_assert.F90:51
 |   |
 |   +-> true: 1 of 2 assertions succeed.
 |   |   |
 |   |   +-> Assertion #1 failed with reason: x (false) true y (N/A)
 |   |   +-> Check line: test_assert.F90:56
 |   |
 |
 +-> Summary:
 |   +-> Boolean: 2 of 4 assertions succeed.

////////////////////////////////////////////////////////////////////////////////


//////////////////////////// Report of Suite: Equal /////////////////////////////

 +-> Details:
 |   |
 |   +-> string: 3 of 6 assertions succeed.
 |   |   |
 |   |   +-> Assertion #1 failed with reason: x (abc) == y (abcd)
 |   |   +-> Check line: test_assert.F90:67
 |   |   |
 |   |   +-> Assertion #3 failed with reason: x (abc) == y (abd)
 |   |   +-> Check line: test_assert.F90:70
 |   |   |
 |   |   +-> Assertion #5 failed with reason: x (abc) == y (abd)
 |   |   +-> Check line: test_assert.F90:73
 |   |
 |   +-> integer: 12 of 24 assertions succeed.
 |   |   |
 |   |   +-> Assertion #1 failed with reason: x (1) == y (2)
 |   |   +-> Check line: test_assert.F90:78
 |   |   |
 |   |   +-> Assertion #3 failed with reason: x (1) == y (2)
 |   |   +-> Check line: test_assert.F90:80
 |   |   |
 |   |   +-> Assertion #5 failed with reason: x (1) == y (2)
 |   |   +-> Check line: test_assert.F90:82
 |   |   |
 |   |   +-> Assertion #7 failed with reason: x (1) == y (2)
 |   |   +-> Check line: test_assert.F90:84
 |   |   |
 |   |   +-> Assertion #9 failed with reason: x (1) == y (2)
 |   |   +-> Check line: test_assert.F90:87
 |   |   |
 |   |   +-> Assertion #11 failed with reason: x (1) == y (2)
 |   |   +-> Check line: test_assert.F90:89
 |   |   |
 |   |   +-> Assertion #13 failed with reason: x (1) == y (2)
 |   |   +-> Check line: test_assert.F90:91
 |   |   |
 |   |   +-> Assertion #15 failed with reason: x (1) == y (2)
 |   |   +-> Check line: test_assert.F90:93
 |   |   |
 |   |   +-> Assertion #17 failed with reason: x (1) == y (2)
 |   |   +-> Check line: test_assert.F90:97
 |   |   |
 |   |   +-> Assertion #19 failed with reason: x (1) == y (2)
 |   |   +-> Check line: test_assert.F90:101
 |   |   |
 |   |   +-> Assertion #21 failed with reason: x (1) == y (2)
 |   |   +-> Check line: test_assert.F90:105
 |   |   |
 |   |   +-> Assertion #23 failed with reason: x (1) == y (2)
 |   |   +-> Check line: test_assert.F90:109
 |   |
 |   +-> real: 6 of 12 assertions succeed.
 |   |   |
 |   |   +-> Assertion #1 failed with reason: x ( 1.000) == y ( 2.000)
 |   |   +-> Check line: test_assert.F90:115
 |   |   |
 |   |   +-> Assertion #3 failed with reason: x ( 1.000) == y ( 2.000)
 |   |   +-> Check line: test_assert.F90:117
 |   |   |
 |   |   +-> Assertion #5 failed with reason: x ( 1.000) == y ( 2.000)
 |   |   +-> Check line: test_assert.F90:120
 |   |   |
 |   |   +-> Assertion #7 failed with reason: x ( 1.000) == y ( 2.000)
 |   |   +-> Check line: test_assert.F90:122
 |   |   |
 |   |   +-> Assertion #9 failed with reason: x ( 1.000) == y ( 2.000)
 |   |   +-> Check line: test_assert.F90:125
 |   |   |
 |   |   +-> Assertion #11 failed with reason: x ( 1.000) == y ( 2.000)
 |   |   +-> Check line: test_assert.F90:127
 |   |
 |
 +-> Summary:
 |   +-> Equal: 21 of 42 assertions succeed.

////////////////////////////////////////////////////////////////////////////////


///////////////////////// Report of Suite: great_then ///////////////////////////

 +-> Details:
 |   |
 |   +-> integer: 12 of 24 assertions succeed.
 |   |   |
 |   |   +-> Assertion #1 failed with reason: x (1) > y (1)
 |   |   +-> Check line: test_assert.F90:138
 |   |   |
 |   |   +-> Assertion #3 failed with reason: x (1) > y (1)
 |   |   +-> Check line: test_assert.F90:140
 |   |   |
 |   |   +-> Assertion #5 failed with reason: x (1) > y (1)
 |   |   +-> Check line: test_assert.F90:142
 |   |   |
 |   |   +-> Assertion #7 failed with reason: x (1) > y (1)
 |   |   +-> Check line: test_assert.F90:144
 |   |   |
 |   |   +-> Assertion #9 failed with reason: x (1) > y (2)
 |   |   +-> Check line: test_assert.F90:147
 |   |   |
 |   |   +-> Assertion #11 failed with reason: x (1) > y (2)
 |   |   +-> Check line: test_assert.F90:149
 |   |   |
 |   |   +-> Assertion #13 failed with reason: x (1) > y (2)
 |   |   +-> Check line: test_assert.F90:151
 |   |   |
 |   |   +-> Assertion #15 failed with reason: x (1) > y (2)
 |   |   +-> Check line: test_assert.F90:153
 |   |   |
 |   |   +-> Assertion #17 failed with reason: x (1) > y (2)
 |   |   +-> Check line: test_assert.F90:157
 |   |   |
 |   |   +-> Assertion #19 failed with reason: x (1) > y (2)
 |   |   +-> Check line: test_assert.F90:162
 |   |   |
 |   |   +-> Assertion #21 failed with reason: x (1) > y (2)
 |   |   +-> Check line: test_assert.F90:167
 |   |   |
 |   |   +-> Assertion #23 failed with reason: x (1) > y (2)
 |   |   +-> Check line: test_assert.F90:172
 |   |
 |   +-> real: 6 of 12 assertions succeed.
 |   |   |
 |   |   +-> Assertion #1 failed with reason: x ( 1.000) > y ( 1.000)
 |   |   +-> Check line: test_assert.F90:178
 |   |   |
 |   |   +-> Assertion #3 failed with reason: x ( 1.000) > y ( 1.000)
 |   |   +-> Check line: test_assert.F90:180
 |   |   |
 |   |   +-> Assertion #5 failed with reason: x ( 1.000) > y ( 2.000)
 |   |   +-> Check line: test_assert.F90:183
 |   |   |
 |   |   +-> Assertion #7 failed with reason: x ( 1.000) > y ( 2.000)
 |   |   +-> Check line: test_assert.F90:185
 |   |   |
 |   |   +-> Assertion #9 failed with reason: x ( 1.000) > y ( 2.000)
 |   |   +-> Check line: test_assert.F90:188
 |   |   |
 |   |   +-> Assertion #11 failed with reason: x ( 1.000) > y ( 2.000)
 |   |   +-> Check line: test_assert.F90:190
 |   |
 |
 +-> Summary:
 |   +-> great_then: 18 of 36 assertions succeed.

////////////////////////////////////////////////////////////////////////////////
```

**Comment by dongli** [comment]
Okay, if that are intentional failures, I think you should add a comment on that.

**Comment by JHenneberg** [comment]
in general when testing a module or project of course everything should pass. In this case i also tested if the failing of the assertions subroutines works as intended. Thats a bit missleading you are right. I will write a comment on this.

**Comment by dongli** [comment]
Thanks for your continuous contribution~

**Comment by JHenneberg** [comment]
you are welcome. I am using the library myself, if you would not provide the inital version I had to code it completly by myself.

**Pull request merged**
